package org.apache.opennlp.gpu.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Model class representing data structures.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ModelClass {
    
    private String name;
    private int value;
    
    // Remove all getters, setters, constructors, equals/hashCode, and toString methods
    // as they will be generated by Lombok
}