package org.apache.opennlp.gpu.model;


/**
 * Model class representing data structures.
 */
public class ModelClass {
    
    private String name;
    private int value;
    
    // Remove all getters, setters, constructors, equals/hashCode, and toString methods
    // as they will be generated by Lombok
}