package org.apache.opennlp.gpu.model;


/**
 * ID: MC-001
 * Requirement: ModelClass must serve as a model registration and metadata class for GPU model type enumeration.
 * Purpose: Enumerates supported GPU model types and provides metadata accessors used by GpuModelFactory for model-type dispatch.
 * Rationale: Centralising model type metadata prevents string-based type comparisons scattered across factory/adapter code.
 * Inputs: Constructor parameters and method arguments as documented per method.
 * Outputs: Provides services and data as defined by the implemented interface(s).
 * Preconditions: JVM initialised; required dependencies available on classpath.
 * Postconditions: Object state is consistent; resources are properly initialised or null.
 * Assumptions: Called in a standard JVM environment with Java 21+ runtime.
 * Side Effects: None; read-only metadata class.
 * Failure Modes: Constructor failure throws RuntimeException; individual methods
 *               document their own failure modes.
 * Error Handling: Exceptions propagated to caller; fallback paths documented per method.
 * Constraints: Thread safety per class-level documentation; memory bounded by config.
 * Verification: Unit and integration tests in src/test; see GpuTestSuite.
 * References: Apache OpenNLP 2.5.8 API; project ARCHITECTURE_OVERVIEW.md.
 */
public class ModelClass {
    
    private String name;
    private int value;
    
    // Remove all getters, setters, constructors, equals/hashCode, and toString methods
    // as they will be generated by Lombok
}